name: Build the application

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]

    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python venv
        run: |
          python -m venv ${GITHUB_WORKSPACE}/.venv
          source ${GITHUB_WORKSPACE}/.venv/bin/activate
          pip install --upgrade pip
          pip install conan==1.66.0 ninja

      - name: Specify conan remotes
        run: |
          source ${GITHUB_WORKSPACE}/.venv/bin/activate
          conan remote add peclet http://conan.kpas.alev.pro False

      - name: Make build directory
        run: mkdir build

      - name: Install dependencies
        working-directory: ./build
        run: |
          source ${GITHUB_WORKSPACE}/.venv/bin/activate
          conan install .. -s compiler.version=14.0

      - name: Build the application
        working-directory: ./build
        run: |
          source ${GITHUB_WORKSPACE}/.venv/bin/activate
          conan build ..
