name: Build the application for Linux

on:
  push:
    branches:
      - master
      - release/*
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]

    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Retrieve the version
        id: gitver
        run: |
          echo "app_version=$(git describe --abbrev=4)" >> $GITHUB_OUTPUT

      - name: Prepare Ubuntu
        run: |
          sudo apt update -y && sudo apt install \
            libegl1-mesa-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libwayland-dev \
            libx11-xcb-dev \
            libx11-xcb-dev \
            libxcb*-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            mesa-common-dev \
            tree

      - name: Set up python venv
        run: |
          python -m venv ${GITHUB_WORKSPACE}/.venv
          source ${GITHUB_WORKSPACE}/.venv/bin/activate
          pip install --upgrade pip
          pip install conan==1.66.0 ninja

      - name: Specify conan remotes
        run: |
          source ${GITHUB_WORKSPACE}/.venv/bin/activate
          conan remote add peclet http://conan.kpas.alev.pro False

      - name: Make build directory
        run: mkdir build && mkdir unixcmd-${{ steps.gitver.outputs.app_version }}-${{ matrix.os }}

      - name: Install dependencies
        working-directory: ./build
        run: |
          source ${GITHUB_WORKSPACE}/.venv/bin/activate
          conan install .. -s compiler.version=9

      - name: Build the application
        working-directory: ./build
        run: |
          source ${GITHUB_WORKSPACE}/.venv/bin/activate
          conan build ..
          tree .
          ldd ./bin/unixcmd

      - name: Generate package
        run: |
          source ${GITHUB_WORKSPACE}/.venv/bin/activate
          conan package -bf ./build -pf ./unixcmd-${{ steps.gitver.outputs.app_version }}-${{ matrix.os }} .
          tree ./unixcmd-${{ steps.gitver.outputs.app_version }}-${{ matrix.os }}

      - name: Zipping package
        run: |
          tar -cJvf \
            unixcmd-${{ steps.gitver.outputs.app_version }}-${{ matrix.os }}.tar.xz \
            --exclude 'conaninfo.txt' \
            --exclude 'conanmanifest.txt' \
            ./unixcmd-${{ steps.gitver.outputs.app_version }}-${{ matrix.os }}

      - name: Uploading archive
        uses: actions/upload-artifact@v4
        if: ${{ !startsWith(github.ref_name, 'release/') && github.ref_type != 'tag' }}
        with:
          name: unixcmd-${{ steps.gitver.outputs.app_version }}-${{ matrix.os }}
          path: unixcmd-${{ steps.gitver.outputs.app_version }}-${{ matrix.os }}.tar.xz
          compression-level: 0

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref_name, 'release/') || github.ref_type == 'tag' }}
        with:
          files:
            unixcmd-${{ steps.gitver.outputs.app_version }}-${{ matrix.os }}.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}